name: deploy-sonatype

on:
  workflow_dispatch:
    inputs:
      username:
        required: true

jobs:
  build-gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Mask workflow inputs
        uses: levibostian/action-hide-sensitive-inputs@v1

      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 19

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.0.2

      - name: Gradle build
        run: ./gradlew build testClasses -x test

      - name: Gradle test
        run: ./gradlew test

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            build/libs
            build/reports

      - name: Gradle publish to Sonatype
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeRepo: ${{ secrets.SONATYPE_REPO }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ inputs.username }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
        run: ./gradlew publishSonatypePublicationToSonatypeRepository