name: matrix_test

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  provider-list:
    runs-on: ubuntu-latest
    outputs:
      test-classes: ${{ steps.images-matrix.outputs.images }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: List provider test classes
        id: test-classes
        run: echo "h1=h1" >> "$GITHUB_OUTPUT"
#        run: ls src/test/java/dev/harrel/jsonschema/providers/ | sed 's/\.java$//' >> "$GITHUB_OUTPUT"

  matr:
    needs: provider-list
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-class: ${{ needs.provider-list.outputs.test-classes }}

    steps:
      - uses: actions/checkout@v3
      - run: echo "hello"