name: matrix_test

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  provider-list:
    runs-on: ubuntu-latest
    outputs:
      test-classes: ${{ steps.test-classes.outputs.test-classes }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: List provider test classes
        id: test-classes
        run: |
          CLASSES = ls src/test/java/dev/harrel/jsonschema/providers/ | sed 's/\.java$//' | jq -R -s -c 'split("\n")[:-1]'
          echo "test-classes=$CLASSES" >> "$GITHUB_OUTPUT"

  matr:
    needs: provider-list
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-class: ${{ needs.provider-list.outputs.test-classes }}

    steps:
      - uses: actions/checkout@v3
      - run: echo "hello"